# Write your MySQL query statement below
SELECT R.CONTEST_ID , ROUND(
        COUNT(R.user_id) * 100.0 /
        (SELECT COUNT(*) FROM Users),
        2) AS PERCENTAGE
FROM REGISTER AS R 
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID 
