# Write your MySQL query statement below
-- SELECT ST.STUDENT_ID, ST.STUDENT_NAME, E.SUBJECT_NAME, COUNT() AS ATTENDED_EXAMS
-- FROM STUDENTS AS ST
-- INNER JOIN
-- EXAMINATIONS AS E
-- ON ST.STUDENT_ID = E.STUDENT_ID
-- ORDER BY ST.STUDENT_ID, E.SUBJECT_NAME

SELECT S.STUDENT_ID, S.STUDENT_NAME, SUB.SUBJECT_NAME, COUNT(E.STUDENT_ID)  AS ATTENDED_EXAMS
FROM STUDENTS AS S
CROSS JOIN
SUBJECTS AS SUB
LEFT JOIN
EXAMINATIONS AS E
ON S.STUDENT_ID = E.STUDENT_ID 
AND SUB.SUBJECT_NAME= E.SUBJECT_NAME
GROUP BY S.STUDENT_ID,S.STUDENT_ID, SUB.SUBJECT_NAME
ORDER BY S.STUDENT_ID,SUB.SUBJECT_NAME